name: App Runner with GitHub

on:
  push:
    branch:
    - main
  pull_request:
    branch:
    - main

jobs:
  build: 
   runs-on: ubuntu-latest
   steps:
    - name: checkout repository 
      uses: actions/checkout@v4

    - name: Set up Python
        uses: actions/python@v3
        with:
          python-version: '3.12.6'  

      - name: Install dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: |-
            $(cat requirements.txt)
          requirements: requirements.txt

      - name: Run application
        run: |
          cd apprunner-demo
          python app.py



  